### ISSUE TITLE
What is the jms queue configuration in standalone-full.xml ?

### ISSUE THREAD

**Issue by cassiusvm** [karlnicholas/dukes-forest#1]
Hello,

What is the jms queue configuration in standalone-full.xml, please?

**Comment by karlnicholas** [comment]
I guess I should put that in the readme.md file. Thanks for pointing that out. Also, I probably said that standalone-full is required, but in case I didn't, please note that it is.

```
<jms-queue name="OrderQueue">
    <entry name="java:global/jms/queue/OrderQueue"/>
    <durable>true</durable>
</jms-queue>
```

**Comment by cassiusvm** [comment]
Hello,

Thank you very much.

I'm using Wildfly 10.0.0.Final, I had to use the following instead: `<jms-queue name="OrderQueue" entries="java:global/jms/queue/OrderQueue" durable="true" />`

**Comment by karlnicholas** [comment]
Thanks. I havn't tried it on wildly 10 yet but I will.

**Comment by karlnicholas** [comment]
Updated readme.me.
