### ISSUE TITLE
Suggestion to XA Datasource for MySQL

### ISSUE THREAD

**Issue by cassiusvm** [karlnicholas/dukes-forest#6]
Hello,

I would like to suggest the following XA Datasource for MySQL (you can create such configuration on Wildfly Server Configuration online):

```
<datasources>
<xa-datasource jndi-name="java:/databaseXADS" pool-name="databaseXADS" enabled="true" use-ccm="true">
    <xa-datasource-property name="ServerName">
        localhost
    </xa-datasource-property>
    <xa-datasource-property name="DatabaseName">
        databasedb
    </xa-datasource-property>
    <driver>com.mysql</driver>
    <security>
        <user-name>username</user-name>
        <password>password</password>
    </security>
    <validation>
        <valid-connection-checker class-name="org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLValidConnectionChecker"/>
        <background-validation>true</background-validation>
        <exception-sorter class-name="org.jboss.jca.adapters.jdbc.extensions.mysql.MySQLExceptionSorter"/>
    </validation>
</xa-datasource>
<drivers>
    <driver name="com.mysql" module="com.mysql">
        <xa-datasource-class>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</xa-datasource-class>
    </driver>
</drivers>
</datasources>
```

**Comment by karlnicholas** [comment]
When you say you can create such a configuration online, where do you mean? I like the datasource, I'd like to know about this online thing you mention.

**Comment by cassiusvm** [comment]
Hello,

It’s Wildfly Management Console, when you open http://localhost:8080, there is a configuration page with a wizard for XA Datasource.

On Wed, Feb 10, 2016 at 7:12 AM -0800, "Karl Nicholas" notifications@github.com wrote:

When you say you can create such a configuration online, where do you mean? I like the datasource, I'd like to know about this online thing you mention.

---

**Comment by karlnicholas** [comment]
Updated to XA Datasource because multiple resources are transaction in single method. See, for example. com.forest.handlers.DeliveryHandler#onNewOrder.
